FROM python:3.6.4-alpine3.7

WORKDIR /SensorUmidadeTemperatura

ADD ./SensorUmidadeTemperatura ./
  
COPY SensorUmidadeTemperatura/requirements.txt ./ 

RUN pip install -r /requirements.txt

CMD ["python", "app.py"]

